Name: SamplePythonApplicationWithTestCodeCoverage
SchemaVersion: "1.0"

# Optional - Set automatic triggers.
Triggers:
  - Type: Push
    Branches:
      - main

# Required - Define action configurations.
Actions:
  Quality:
    Identifier: aws-actions/cawstestbeta-test@v1
    Inputs:
      Sources:
        - WorkflowSource
    Outputs:
      Artifacts:
        - Name: Artifact_Test
          Files:
            - "**/*"
      Reports:
        IntegrationTests:
          IncludePaths:
            - test_report.xml
          Format: JUNITXML
        CoverageReport:
          IncludePaths:
            - coverage.xml
          Format: COBERTURAXML
    Configuration:
      Steps:
        - Run: pip install -r requirements.txt
        - Run: coverage run --source=src/. --junitxml=test_report.xml -m pytest
        - Run: coverage report
        - Run: coverage xml -o cover_coverage.xml
    Compute: Linux.x86-64.Large
