Name: SamplePythonApplicationWithTestCodeCoverage
SchemaVersion: "1.0"

# Optional - Set automatic triggers.
Triggers:
  - Type: Push
    Branches:
      - main

# Required - Define action configurations.
Actions:
  Quality:
    Identifier: aws-actions/cawstestbeta-test@v1
    Inputs:
      Sources:
        - WorkflowSource
    Outputs:
      Artifacts:
        - Name: Artifact_Test
          Files:
            - "**/*"
      Reports:
        IntegrationTests:
          IncludePaths:
            - test_report.xml
          Format: JUNITXML
        CoverageReport:
          IncludePaths:
            - code_coverage.xml
          Format: COBERTURAXML
    Configuration:
      Steps:
        - Run: yum update -y
        - Run: yum install -y python3
        - Run: curl https://bootstrap.pypa.io/pip/get-pip.py -o get-pip.py
        - Run: python3 get-pip.py
        - Run: pip install -r requirements.txt
        - Run: coverage run --source=src/. -m pytest --junitxml=test_report.xml
        - Run: coverage xml -o code_coverage.xml
